
# Each list of articles in the toread.md file
# Format is shortcut: title
# The shortcut is used by the ./pop function 
# To get the first article QID in the toread file 
# After the title is matched by regular expression.

lists:
# - shortcut: Title of header in toread.md  
  main: Main Articles
  other: Other
queries:
  main:
   - https://w.wiki/4T2P # Articles about Wikidata published in eLife
  other:
   - https://w.wiki/4T2W # Articles about Wikidata in 2021 with at least 01 female author